packages:
  - examples
  - packages/**

ignoredBuiltDependencies:
  - esbuild

overrides:
  fast-xml-parser: '>=5.3.6'
  '@vitest/expect': $vitest
  '@vitest/mocker': $vitest
  '@vitest/spy': $vitest
