packages:
  - examples
  - packages/**

allowBuilds:
  esbuild: false

# 重複排除
dedupePeers: true

overrides:
  fast-xml-parser: '>=5.3.6'
  '@vitest/expect': $vitest
  '@vitest/mocker': $vitest
  '@vitest/spy': $vitest

# リリースから一定時間経過していないか、信頼性低下したパッケージはインストールしない
minimumReleaseAge: 2880
trustPolicy: no-downgrade
trustPolicyExclude:
  - 'semver@6.3.1'

# 特殊なソースからの依存関係をインストールしない
blockExoticSubdeps: true
