packages:
  - examples
  - packages/**

allowBuilds:
  esbuild: false

# 重複排除
dedupePeers: true

catalog:
  vitest: 4.1.9
  '@vitest/browser': 4.1.9
  '@vitest/coverage-v8': 4.1.9
  '@vitest/expect': 4.1.9
  '@vitest/mocker': 4.1.9
  '@vitest/spy': 4.1.9

overrides:
  esbuild: '>=0.28.1'
  fast-xml-parser: '>=5.3.6'
  '@vitest/expect': 'catalog:'
  '@vitest/mocker': 'catalog:'
  '@vitest/spy': 'catalog:'

# リリースから一定時間経過していないか、信頼性低下したパッケージはインストールしない
minimumReleaseAge: 2880 # 2d
minimumReleaseAgeIgnoreMissingTime: false
trustPolicy: no-downgrade
trustPolicyExclude:
  - 'semver@6.3.1'

# 特殊なソースからの依存関係をインストールしない
blockExoticSubdeps: true
