packages:
  - examples
  - packages/**

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - lefthook

overrides:
  fast-xml-parser: '>=5.3.4'
  '@vitest/expect': $vitest
  '@vitest/mocker': $vitest
  '@vitest/spy': $vitest
